language: go

go:
 - 1.6
 - tip

install:
  - go get github.com/siddontang/ledisdb/ledis
  - go get github.com/smartystreets/goconvey

script:
  - go test ./... -v

notifications:
  email:
    - travis@deluan.com
